import assert from 'node:assert/strict';
import {validDate, getArchive} from '../lib/archive.js';
assert(validDate('2026-10-08'));
assert(!validDate('2026-02-30'));
assert(!validDate('2026-10-08&offset=999'));
delete process.env.SUPABASE_URL;
assert.equal((await getArchive()).status,'unconfigured');
process.env.SUPABASE_URL='https://example.supabase.co';
process.env.SUPABASE_PUBLISHABLE_KEY='test-publishable';
let observed;
global.fetch=async(url, options)=>{observed={url,options}; return {ok:true,json:async()=>Array.from({length:49},(_,i)=>({id:i,object_path:`device/${i}.jpg`}))};};
const result=await getArchive('2026-10-08',2);
assert.equal(result.captures.length,48); assert(result.hasMore);
const query=new URL(observed.url).searchParams;
assert.deepEqual(query.getAll('captured_at'),['gte.2026-10-08T00:00:00Z','lt.2026-10-09T00:00:00.000Z']);
assert.equal(query.get('offset'),'96');
assert.equal(observed.options.headers.apikey,'test-publishable');
global.fetch=async()=>({ok:false});
assert.equal((await getArchive()).status,'error');
console.log('PASS: archive date validation, configuration, pagination, UTC boundaries and error states');
